" Load custom settings
"
"source $HOME/.vim/startup/vundle.vim
source $HOME/.vim/startup/vim-plug.vim
source $HOME/.vim/startup/vimacs.vim
source $HOME/.vim/startup/easymotion.vim
source $HOME/.vim/startup/mappings.vim
source $HOME/.vim/startup/settings.vim
source $HOME/.vim/startup/ctrlpfunky.vim
"source $HOME/.vim/startup/airline.vim
"source $HOME/.vim/startup/nerdtree.vim
source $HOME/.vim/startup/tmuxline.vim
"source $HOME/.vim/startup/promptline.vim
source $HOME/.vim/startup/vim-smile.vim
source $HOME/.vim/startup/neocomplete.vim
source $HOME/.vim/startup/WatchForChanges.vim
"source $HOME/.vim/startup/multiple-cursors.vim

