airline.vim	airline.vim	/airline.vim
airline2.vim	airline2.vim	/airline2.vim
ctrlpfunky.vim	ctrlpfunky.vim	/ctrlpfunky.vim
easymotion.vim	easymotion.vim	/easymotion.vim
easymotion2.vim	easymotion2.vim	/easymotion2.vim
easymotion3.vim	easymotion3.vim	/easymotion3.vim
gsettings.vim	gsettings.vim	/gsettings.vim
mappings.vim	mappings.vim	/mappings.vim
multiple-cursors.vim	multiple-cursors.vim	/multiple-cursors.vim
neocomplete.vim	neocomplete.vim	/neocomplete.vim
nerdtree.vim	nerdtree.vim	/nerdtree.vim
pathogen.vim	pathogen.vim	/pathogen.vim
powerline.vim	powerline.vim	/powerline.vim
promptline.vim	promptline.vim	/promptline.vim
settings.vim	settings.vim	/settings.vim
tags.vim	tags.vim	/tags.vim
tmuxline.vim	tmuxline.vim	/tmuxline.vim
vim-plug.vim	vim-plug.vim	/vim-plug.vim
vim-smile.vim	vim-smile.vim	/vim-smile.vim
vimacs.vim	vimacs.vim	/vimacs.vim
vimrc	vimrc	/vimrc
vundle.vim	vundle.vim	/vundle.vim
